events {}
http {
  resolver 127.0.0.11 valid=30s ipv6=off;
  resolver_timeout 5s;

  upstream auth_backend {
    zone auth_backend 64k;
    server auth:9999 resolve;
  }
  upstream rest_backend {
    zone rest_backend 64k;
    server rest:3000 resolve;
  }
  upstream storage_backend {
    zone storage_backend 64k;
    server storage:5000 resolve;
  }

  server {
    listen 8000;
    server_tokens off;
    client_max_body_size 50m;

    location = /health { return 204; }
    location /auth/v1/ {
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header apikey $http_apikey;
      proxy_set_header Authorization $http_authorization;
      proxy_pass http://auth_backend/;
    }
    location /rest/v1/ {
      proxy_set_header apikey $http_apikey;
      proxy_set_header Authorization $http_authorization;
      proxy_pass http://rest_backend/;
    }
    location /storage/v1/ {
      proxy_set_header apikey $http_apikey;
      proxy_set_header Authorization $http_authorization;
      proxy_pass http://storage_backend/;
    }
    location / { return 404; }
  }
}
